student

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -77,6 +77,8 @@ jobs:
           echo "Testing upload:"
           echo "test" > test.txt
           aws s3 cp test.txt s3://${{ secrets.AWS_S3_BUCKET }}/${{ steps.vars.outputs.s3_path }}/test.txt --sse AES256 || echo "Failed to upload test file"
+          echo "Testing delete:"
+          aws s3 rm s3://${{ secrets.AWS_S3_BUCKET }}/${{ steps.vars.outputs.s3_path }}/test.txt || echo "Failed to delete test file"
 
       - name: Deploy to S3
         run: aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }}/${{ steps.vars.outputs.s3_path }} --delete --sse AES256 --debug
